ALTER TABLE projects ADD COLUMN IF NOT EXISTS existing_url TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS benchmark_url TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS new_site_url TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS widget_installed BOOLEAN DEFAULT false;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS review_token TEXT UNIQUE;
